### ISSUE TITLE
Update permissions after composer install

### ISSUE THREAD

**Issue by lucasfrey** [heyday/silverstripe-dataobjectpreview#3]
I got an issue when I'm running a composer install on a distant server. The preview is returning a Page not found `500` because of permissions issue.

I need to run something like : `sudo chmod -R ugo+w [...]/silverstripe-dataobjectpreview`
Unfortunately I don't have access to the distant server.

Is there a way we could add a post script like this : 

```
    "scripts": {
        "post-install-cmd": [
            "sudo chmod -R ugo+w silverstripe-dataobjectpreview"
        ]
    }
```

?

**Comment by stecman** [comment]
You can definitely do that in the root `composer.json` file for your project, but running scripts in the `composer.json` of dependencies [isn't supported by Composer](/composer/composer/issues/1193)). Even if this was supported, there's not really a one-size-fits-all command here, since it depends on your server setup.

Using `sudo` and changing all the code's permissions seems excessive - have you tested something like this out?

```json
"scripts": {
    "post-install-cmd": [
        "chmod ugo+wx silverstripe-dataobjectpreview/cache"
    ]
}
```

On a related note, permissions for the `cache` dir aren't mentioned at all in the readme... should probably fix that.

**Comment by lucasfrey** [comment]
Yeah that's exactly what I was about to do, I'll put that on a `dev` branch first and see how if it works

Thanks for your input mate.

**Comment by lucasfrey** [comment]
Hey @stecman,

So you mean if I try to install for example the `heyday/silverstripe-slices` module, the command won't run because it's a sub-dependency ?

**Comment by stecman** [comment]
If the snippet above is in your project's `composer.json`, it should run any time `composer install` is run. If the snippet was put in this module's `composer.json`, it would never run.

Composer prints any script commands it's running by default, so it should be easy to see what's running  provided you can see the output of `composer install` on your remote server:

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
...
Generating autoload files
> chmod ugo+wx test
```

**Comment by lucasfrey** [comment]
That's great, you think I should still add it to this module and tag it ? I can create a pull request.
